table route_dim
	lineageTag: 971927aa-965b-4e32-9ca8-2a98d9ff54e1

	column route_id
		dataType: string
		lineageTag: aa4317c5-3570-49c1-ada2-3667a5f533e8
		summarizeBy: none
		sourceColumn: route_id

		annotation SummarizationSetBy = Automatic

	column origin_code
		dataType: string
		lineageTag: 491af95a-1556-4c5d-8e0d-213570f7dc8f
		summarizeBy: none
		sourceColumn: origin_code

		annotation SummarizationSetBy = Automatic

	column dest_code
		dataType: string
		lineageTag: 40308b47-740f-4ce2-8164-20495fcf9d85
		summarizeBy: none
		sourceColumn: dest_code

		annotation SummarizationSetBy = Automatic

	column origin_city
		dataType: string
		lineageTag: 82cb1015-03e0-4d1c-a2c0-a456234da1f8
		summarizeBy: none
		sourceColumn: origin_city

		annotation SummarizationSetBy = Automatic

	column dest_city
		dataType: string
		lineageTag: 69a11b68-b09b-463b-9a3a-ba48ad05292f
		summarizeBy: none
		sourceColumn: dest_city

		annotation SummarizationSetBy = Automatic

	column route_label
		dataType: string
		lineageTag: fe372024-4436-46fd-8744-48ea8d089afb
		summarizeBy: none
		sourceColumn: route_label

		annotation SummarizationSetBy = Automatic

	column distance_km
		dataType: int64
		formatString: 0
		lineageTag: 68cc411f-114c-4082-bafe-6d09d906eb16
		summarizeBy: none
		sourceColumn: distance_km

		annotation SummarizationSetBy = Automatic

	column flight_time_hrs
		dataType: double
		lineageTag: 3349f3fa-9e05-4d85-8c9d-53f38e35d7b0
		summarizeBy: none
		sourceColumn: flight_time_hrs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column seats
		dataType: int64
		formatString: 0
		lineageTag: 39128ec8-9800-4a56-a51e-3fb63e6ce84b
		summarizeBy: none
		sourceColumn: seats

		annotation SummarizationSetBy = Automatic

	column daily_frequency
		dataType: int64
		formatString: 0
		lineageTag: 8523a889-ae38-4a4c-9445-8e26616a99cf
		summarizeBy: none
		sourceColumn: daily_frequency

		annotation SummarizationSetBy = Automatic

	column route_tier
		dataType: string
		lineageTag: 67f40750-e983-4f45-822a-3ceb0ee5468c
		summarizeBy: none
		sourceColumn: route_tier

		annotation SummarizationSetBy = Automatic

	column base_total_fare
		dataType: int64
		formatString: 0
		lineageTag: 8e7fea2c-06dd-4add-a583-33d67b883cc1
		summarizeBy: none
		sourceColumn: base_total_fare

		annotation SummarizationSetBy = Automatic

	column ask_per_flight
		dataType: int64
		formatString: 0
		lineageTag: c27393a5-2aa3-46b2-a119-a81acc8967ba
		summarizeBy: none
		sourceColumn: ask_per_flight

		annotation SummarizationSetBy = Automatic

	column aircraft_type
		dataType: string
		lineageTag: cea676ec-1519-4d66-9c07-4029bd2003ac
		summarizeBy: none
		sourceColumn: aircraft_type

		annotation SummarizationSetBy = Automatic

	partition route_dim = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\steph\Downloads\route_dim.csv"),[Delimiter=",", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"route_id", type text}, {"origin_code", type text}, {"dest_code", type text}, {"origin_city", type text}, {"dest_city", type text}, {"route_label", type text}, {"distance_km", Int64.Type}, {"flight_time_hrs", type number}, {"seats", Int64.Type}, {"daily_frequency", Int64.Type}, {"route_tier", type text}, {"base_total_fare", Int64.Type}, {"ask_per_flight", Int64.Type}, {"aircraft_type", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

